create table if not exists public.community_reactions (
  id bigint generated by default as identity primary key,
  comment_id uuid not null references public.predictions_comments(id) on delete cascade,
  reaction_type text not null check (reaction_type in ('fire','bullseye','laugh','eyes')),
  voter_hash text not null,
  created_at timestamptz not null default now(),
  unique (comment_id, reaction_type, voter_hash)
);

create index if not exists community_reactions_comment_id_idx on public.community_reactions(comment_id);
create index if not exists community_reactions_type_idx on public.community_reactions(reaction_type);

alter table public.community_reactions enable row level security;
revoke all on table public.community_reactions from anon, authenticated;

drop function if exists public.get_community_reaction_counts(uuid[]);
create or replace function public.get_community_reaction_counts(p_comment_ids uuid[])
returns table(comment_id uuid, reaction_type text, reaction_count bigint)
language sql
security definer
set search_path = public
as $$
  select cr.comment_id, cr.reaction_type, count(*)::bigint
  from public.community_reactions cr
  where cr.comment_id = any(coalesce(p_comment_ids, '{}'::uuid[]))
  group by cr.comment_id, cr.reaction_type;
$$;

revoke all on function public.get_community_reaction_counts(uuid[]) from public;
grant execute on function public.get_community_reaction_counts(uuid[]) to anon, authenticated;

create or replace function public.apply_community_reaction(p_comment_id uuid, p_reaction_type text, p_voter_hash text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  removed boolean := false;
begin
  if p_comment_id is null or p_reaction_type not in ('fire','bullseye','laugh','eyes') or coalesce(trim(p_voter_hash),'') = '' then
    raise exception 'invalid_reaction';
  end if;
  if not exists (select 1 from public.predictions_comments where id = p_comment_id and comment is not null and btrim(comment) <> '') then
    raise exception 'comment_not_found';
  end if;
  delete from public.community_reactions
   where comment_id = p_comment_id and reaction_type = p_reaction_type and voter_hash = p_voter_hash;
  if found then
    removed := true;
  else
    insert into public.community_reactions(comment_id, reaction_type, voter_hash)
    values(p_comment_id, p_reaction_type, p_voter_hash);
  end if;
  return not removed;
end;
$$;

revoke all on function public.apply_community_reaction(uuid,text,text) from public;
grant execute on function public.apply_community_reaction(uuid,text,text) to service_role;
